"use client";
import React, { useState } from "react";
import Banner from "./components/Home/Banner";
import Recomendation from "./components/Home/Recomendation";


export default function Home() {
  return (
    <>
      <div className="flex flex-col mt-24 mx-4 sm:mx-20 items-center">
        <Banner />
      </div>
      <div className="mb-10">
        <h2 className="text-lg sm:text-xl font-bold mt-6 ml-10 lg:ml-52 text-gray-800">
          Recommendation
        </h2>
        <Recomendation />
      </div>
    </>
  );
}

"use client";
import { Inter } from "next/font/google";
import { usePathname } from "next/navigation";
import { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/Navbar/Navbar";
import { SessionProvider } from "next-auth/react";

const inter = Inter({ subsets: ["latin"] });
const navbar = ["/", "/search"];



function showNavbar(pathname: string): boolean {
  if (navbar.includes(pathname)) {
    return true;
  }
  if (pathname.startsWith("/article")) {
    return true;
  }
  return false;
}

export const layoutMetadata: Metadata = {
  title: "KMS KNPK",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathname = usePathname();

  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider>
          {showNavbar(pathname) && <Navbar />}
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
